# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 19:41
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170307_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='avgRating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='barber',
            name='profilePic',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='client',
            name='avgRating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/clients'), upload_to=b''),
        ),
    ]
