# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 19:44
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170316_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='profilePic',
            field=models.ImageField(blank=True, height_field='height_field', null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/clients'), upload_to=b'', width_field='width_field'),
        ),
    ]
