# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20170316_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='profilePic',
            field=models.ImageField(blank=True, default='../eclips/media/no-img.png', height_field='height_field', null=True, upload_to='media/clients', width_field='width_field'),
        ),
    ]
