# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20170316_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='client',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='client',
            name='profilePic',
            field=models.ImageField(blank=True, default='../eclips/media/no-img.png', null=True, upload_to='media/clients'),
        ),
    ]
