# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20170316_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profilePic',
            field=models.ImageField(null=True, upload_to='/media/clients/'),
        ),
    ]
