# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20170317_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='barbers'),
        ),
        migrations.AlterField(
            model_name='client',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='clients'),
        ),
    ]
