# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20170318_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='gallery',
            field=models.ImageField(blank=True, null=True, upload_to='barbers/gallery'),
        ),
    ]
