# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_barber_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ImageField(blank=True, null=True, upload_to='barbers/gallery')),
            ],
        ),
        migrations.RemoveField(
            model_name='barber',
            name='gallery',
        ),
        migrations.AddField(
            model_name='gallery',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Barber'),
        ),
    ]
