# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20170318_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='isCompleted',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='writer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
